// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string": "text".  HINT: For your key names, use the
// English string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//

/** @class

  @version 0.1
  @author Suvajit Gupta
*/
SC.stringsFor('English', {

  "_ActionsButtonTooltip": "Globally available actions",
  "_Activated:": "Activated: ",
  "_Active": "Active",
  "_Add": "Add",
  "_AddProjectTooltip": "Add a new project",
  "_AddTaskTooltip": "Add a new task, to same project/assignee if there is a selected task",
  "_AddUserTooltip": "Add a new user",
  "_All": "All",
  "_AllTasks": "All Tasks",
  "_AllTooltip": "Full Plate: all tasks",
  "_Apply": "Apply",
  "_Assignee:": "Assignee: ",
  "_AssigneeNotLoaded": "Not loaded",
  "_AssigneeOverloaded": "Overloaded",
  "_AssigneeProperlyLoaded": "Properly loaded",
  "_AssigneeUnderLoaded": "Under loaded",
  "_Assignees:": "Assignees: ",
  "_AutoSave": "AutoSave",
  "_Bug": "Bug",
  "_Cancel": "Cancel",
  "_ClippyTooltip": "Copy ID/Name of selected tasks to clipboard",
  "_Close": "Close",
  "_Completed": "Completed",
  "_CompletedTooltip": "Ready for Primetime: what's done & passed",
  "_Confirmation": "Confirmation",
  "_Copy": ": copy",
  "_CopyID/Name": "Copy ID/Name",
  "_CopyLinkLocation": "Copy Link Location",
  "_CreateMissingUsers": "Create Missing Users",
  "_CreateMissingUsersTooltip": "Automatically create new users for unknown assignees/submitters during import",
  "_Created:": "Created: ",
  "_Credits": "Credits: Suvajit Gupta, Sean Eidemiller, Josh Holt, and Matt Grantham",
  "_DataLoadFailed": "Data load failed ",
  "_DataLoaded": "Data loaded ",
  "_DataSaved": "Data saved ",
  "_DataSaveError": "Data save failed ",
  "_Delete": "Delete",
  "_DeleteProjectTooltip": "Delete selected projects",
  "_DeleteTaskTooltip": "Delete selected tasks",
  "_DeleteUserTooltip": "Delete selected users",
  "_Description:": "Description:",
  "_DescriptionHint": "Enter detailed notes...",
  "_Developer": "Developer",
  "_DisplayModeTooltip": "Display Mode: click on left for team summary; click on right to see tasks",
  "_DisplayedUsers": " users displayed, ",
  "_Done": "Done",
  "_DoneEffortRangeWarning": " (completed task shouldn't have an effort range)",
  "_DontCare": "Don't Care",
  "_Duplicate": "Duplicate",
  "_Effort:": "Effort:",
  "_EffortOnscreenHelp": "May be unspecified, a decimal like '0.25',<br> or a range like '2-3'; in units 'd' or 'h'",
  "_EffortSpecified:": "Effort Specified:",
  "_EffortSpecifiedTooltip": "Show/hide tasks that have effort specified",
  "_Email:": "Email:",
  "_EmailAddress": "Your Email Address",
  "_EmailOnscreenHelp": "Specify to receive Email notifications",
  "_Export": "Export",
  "_Failed": "Failed",
  "_Feature": "Feature",
  "_FilterTooltip": "Filter tasks by type, priority, status, validation, effort specified, recently updated",
  "_FirstLast": "Firstname Lastname",
  "_FormatOnscreenHelpSoftwareMode": "Project Name {TimeLeft} &lt;ActivatedAt&gt; @Status<br>- Task Name {Effort} &lt;Submitter&gt; [Assignee] $Type @Status %Validation<br>| Description (1 or more lines following a Project or Task)",
  "_FormatOnscreenHelpTodoMode": "Project Name {TimeLeft} &lt;ActivatedAt&gt;<br>- Task Name {Effort} &lt;Submitter&gt; [Assignee] @Status<br>| Description (1 or more lines following a Project or Task)",
  "_FullName:": "Full Name:",
  "_Guest": "Guest",
  "_GuestSignup": "Guest Signup",
  "_Has": "Has ",
  "_Hi": "Hi ",
  "_High": "High",
  "_ID": "ID: ",
  "_Import": "Import",
  "_ImportInstructions:": "Paste or type in data to be imported:<br>(see format on right)",
  "_IncompleteEffortWarning": " (total effort incomplete)",
  "_Initials": "Initials",
  "_InvalidEmailAddress": "This email address",
  "_LaunchExportHTML": "Export (HTML)...",
  "_LaunchExportText": "Export (Text)...",
  "_LaunchHelp": "Help...",
  "_LaunchImport": "Import...",
  "_LaunchSettings": "Users/Settings...",
  "_LaunchStatistics": "Statistics...",
  "_LoadingData": "Loading data...",
  "_Login": "Login",
  "_LoginServerAccessError": "Login failed - cannot access server",
  "_LoginAuthenticationError": "Login failed - please try again",
  "_LoginName:": "Login Name:",
  "_LoginSince": "Click to see your tasks; Logged in since ",
  "_Logout": "Logout",
  "_LogoutConfirmation": "Are you sure you want to log out from the application?",
  "_Low": "Low",
  "_Manager": "Manager",
  "_Medium": "Medium",
  "_Name": "Name:",
  "_NewProject": "New Project",
  "_NewTask": "New Task",
  "_No": "No",
  "_OnlineHelp": "Online Help",
  "_Other": "Other",
  "_Passed": "Passed",
  "_Password:": "Password:",
  "_PasswordHint": "Password",
  "_PasswordTooltip": "Has a password",
  "_Planned": "Planned",
  "_Priority": "Priority:",
  "_PriorityTooltip": "Importance of task: must do, plan to do, do if you can",
  "_Project": "Project ",
  "_Project:": "Project: ",
  "_ProjectDeletionConfirmation": "Are you sure you want to delete the selected projects?",
  "_ProjectCountdownTooltip": "Countdown of days left",
  "_ProjectDetails": "Project Details",
  "_Projects": "Projects",
  "_QuickFilters": "QUICK FILTERS",
  "_QuickFiltersTooltip": "Commonly used filters",
  "_RecentlyUpdated:": "Recently Updated:",
  "_RecentlyUpdatedFilterTooltip": "Show/hide recently updated tasks",
  "_RecentlyUpdatedTooltip": "Dot indicates a recently (within last day) created/updated item",
  "_RedFlags:": "Red Flags: ",
  "_RefreshTooltip": "Reload latest Tasks data from the server",
  "_Risky": "Risky",
  "_Role:": "Role:",
  "_SaveConfirmation": "You have unsaved changes - save before logging out?",
  "_SaveTooltip": "Save modified Tasks data to the server",
  "_SendNotifications": "Notifications",
  "_ShowNextTask": "Show next task",
  "_ShowPreviousTask": "Show previous task",
  "_Showstoppers": "Showstoppers",
  "_ShowstoppersTooltip": "Are We There Yet: open high priority defects",
  "_Signup": "Signup",
  "_Statistics": "Statistics",
  "_Status": "Status:",
  "_StatusTooltip": "Development status of task: show progress or obstacles",
  "_Submitter:": "Submitter: ",
  "_SubmitterTooltip": "; Submitted by ",
  "_Submitters:": "Submitters: ",
  "_Summary:": "Summary: ",
  "_System": "System",
  "_TargetDate:": "Target Date:",
  "_TaskDeletionConfirmation": "Are you sure you want to delete the selected tasks?",
  "_TaskEffortTooltip": "Task effort",
  "_TaskIdTooltip": "Task #ID (dashes indicate unsaved, underline indicates watch)",
  "_TaskValidationTooltip": ", background color shows validation",
  "_Tasks": "Tasks",
  "_TaskDetails": "Task Details",
  "_TasksSearchHint": "Task search pattern",
  "_TasksSearchTooltip": "Specify [Assignees] or <Submitters> (use all or part of full/login name separated via commas or spaces - use 'none' for unassigned), #IDs (separated by commas or spaces), or text (to match within task name or description - prefix with a caret to find items that don't match text)",
  "_TasksUnallocated": "Any tasks allocated to deleted projects will become unallocated.",
  "_TasksUnassigned": "Any tasks assigned to deleted users will become unassigned.",
  "_Tester": "Tester",
  "_TimeLeft:": "Time Left:",
  "_TimeLeftOnscreenHelp": "May be unspecified, a decimal like '0.25'; in units 'd' or 'h'",
  "_Toggle": "Toggle ",
  "_Troubled": "Troubled",
  "_TroubledTooltip": "Manage by Exception: what's risky or failed",
  "_Type": "Type:",
  "_TypeTooltip": "Kind of task: user visible functionality, defect fix, or other",
  "_UnallocatedTasks": "Unallocated Tasks",
  "_UnassignedTasks": "Unassigned Tasks",
  "_Unassigned": "Unassigned",
  "_Unfinished": "Unfinished",
  "_UnfinishedTooltip": "Deliver on Commitments: what's left to finish",
  "_Untested": "Untested",
  "_Unvalidated": "Unvalidated",
  "_UnvalidatedTooltip": "Trust but Verify: what's left to validate",
  "_Unwatch": "Unwatch",
  "_Updated:": "Updated: ",
  "_User": "User",
  "_UserDeletionConfirmation": "Are you sure you want to delete the selected users?",
  "_UsersSettings": "Users/Settings",
  "_LoginNameHint": "Login Name",
  "_UserSearchSelectionHint": "User name or email pattern",
  "_UserSearchSelectionTooltip": "Specify pattern to match all or part of users' full/login name or email",
  "_Validation": "Validation:",
  "_ValidationTooltip": "Testing status of completed task - independent verification recommended",
  "_Watch": "Watch",
  "_Yes": "Yes",
  "_assignees": " assignees & ",
  "_description": "description",
  "_displayed": " displayed",
  "_finished": " tasks finished",
  "_left": " tasks left",
  "_projects": " projects & ",
  "_redFlags": " red flags",
  "_selected": " selected",
  "_tasks": " tasks",
  "_total": ", total ",
  "_with": " with "

});
