{"id":"generated.js",
"sources":[
	{"id":"generated.js?sources?0",
		"name":"user",
		"schema":{
			"properties":{
				"_id":{
					"type":"any",
					"optional":true
				},
				"createdAt":{
					"type":"any",
					"optional":true
				},
				"updatedAt":{
					"type":"any",
					"optional":true
				},
				"name":{
					"type":"any",
					"optional":false
				},
				"loginName":{
					"type":"any",
					"optional":false
				},
				"role":{
					"type":"any",
					"optional":false
				},
				"email":{
					"type":"any",
					"optional":true
				},
				"password":{
					"type":"any",
					"optional":true
				},
				"preferences":{
					"type":"object",
					"optional":true
				},
				"authToken":{
					"type":"any",
					"optional":true
				}
			},
			"prototype":{
			},
			"instances":{"$ref":"../user/"}
		}
	},
	{"id":"generated.js?sources?1",
		"name":"project",
		"schema":{
			"properties":{
				"_id":{
					"type":"any",
					"optional":true
				},
				"createdAt":{
					"type":"any",
					"optional":true
				},
				"updatedAt":{
					"type":"any",
					"optional":true
				},
				"name":{
					"type":"any",
					"optional":false
				},
				"description":{
					"type":"any",
					"optional":true
				},
				"timeLeft":{
					"type":"any",
					"optional":true
				},
				"developmentStatus":{
					"type":"any",
					"optional":true
				},
				"activatedAt":{
					"type":"any",
					"optional":true
				}
			},
			"prototype":{
			},
			"instances":{"$ref":"../project/"}
		}
	},
	{"id":"generated.js?sources?2",
		"name":"task",
		"schema":{
			"properties":{
				"_id":{
					"type":"any",
					"optional":true
				},
				"createdAt":{
					"type":"any",
					"optional":true
				},
				"updatedAt":{
					"type":"any",
					"optional":true
				},
				"name":{
					"type":"any",
					"optional":false
				},
				"description":{
					"type":"any",
					"optional":true
				},
				"projectId":{
					"type":"any",
					"optional":true
				},
				"priority":{
					"type":"any",
					"optional":true
				},
				"effort":{
					"type":"any",
					"optional":true
				},
				"submitterId":{
					"type":"any",
					"optional":true
				},
				"assigneeId":{
					"type":"any",
					"optional":true
				},
				"type":{
					"type":"any",
					"optional":true
				},
				"developmentStatus":{
					"type":"any",
					"optional":true
				},
				"validation":{
					"type":"any",
					"optional":true
				}
			},
			"prototype":{
			},
			"instances":{"$ref":"../task/"}
		}
	},
	{"id":"generated.js?sources?3",
		"name":"watch",
		"schema":{
			"properties":{
				"_id":{
					"type":"any",
					"optional":true
				},
				"createdAt":{
					"type":"any",
					"optional":true
				},
				"updatedAt":{
					"type":"any",
					"optional":true
				},
				"taskId":{
					"type":"any",
					"optional":true
				},
				"userId":{
					"type":"any",
					"optional":true
				}
			},
			"prototype":{
			},
			"instances":{"$ref":"../watch/"}
		}
	},
	{"id":"generated.js?sources?4",
		"name":"all",
		"schema":{
			"prototype":{
				"get":function () {
    return serialize(load("user"));
}
			},
			"instances":{"$ref":"../all/"},
			"get":
function () {
    return {users:load("user"), projects:load("project"), tasks:load("task"), watches:load("watch")};
}
,
			"getDelta":
function (timestamp) {
    var query = "updatedAt!=null & updatedAt!=undefined & updatedAt>$1";
    return {users:load("user?" + query, timestamp), projects:load("project?" + query, timestamp), tasks:load("task?" + query, timestamp), watches:load("watch?" + query, timestamp)};
}
,
			"cleanup":
function (timestamp) {
    var monthAgo = Date.now() - 30 * 24 * 60 * 60 * 1000;
    var query = "status=\"deleted\" & updatedAt<$1";
    var len, i;
    var users_to_delete = load("user?" + query, monthAgo);
    for (i = 0, len = users_to_delete.length; i < len; i++) {
        remove(users_to_delete[i]);
    }
    var projects_to_delete = load("project?" + query, monthAgo);
    for (i = 0, len = projects_to_delete.length; i < len; i++) {
        remove(projects_to_delete[i]);
    }
    var tasks_to_delete = load("task?" + query, monthAgo);
    for (i = 0, len = tasks_to_delete.length; i < len; i++) {
        remove(tasks_to_delete[i]);
    }
    var watches_to_delete = load("watch?" + query, monthAgo);
    for (i = 0, len = watches_to_delete.length; i < len; i++) {
        remove(watches_to_delete[i]);
    }
    return {users:users_to_delete, projects:projects_to_delete, tasks:tasks_to_delete, watches:watches_to_delete};
}

		}
	}
]
}